#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'ros-image','console_scripts','ros_image'
__requires__ = 'ros-image'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('ros-image', 'console_scripts', 'ros_image')()
    )
